Better public part and fixes in regards to images
retroherna/rhinventory pull request #54
Opened 2023-01-19 19:19 UTC by tomascapek

2023-01-20 20:44 UTC, Sanqui requested changes
Vypadá to super, mrkni na komentáře

2023-01-20 20:44 UTC, Sanqui commented on rhinventory/admin_views/file.py
> -
Původní logika kódu spočítala MD5ku, pak zkontrolovala jestli takový soubor existuje, a v případě že ne ho uložila. V nové verzi kódu sice stále počítáš MD5ku, zároveň ten soubor ale ukládáš (ve funkci `upload_file()`), a až potom vidím logiku která přeskakuje duplikáty.

2023-01-20 20:44 UTC, Sanqui commented on rhinventory/admin_views/magdb.py
> +            prepared_values["issue_number"] = last_issue.issue_number or 0 + 1
Pozor, `+` má precedenci nad `or`:
```python
>>> 5 or 0 + 1
5
```
Doporučuju ozávorkovat:
```python
(last_issue.issue_number or 0) + 1
```

2023-01-20 20:44 UTC, Sanqui commented on rhinventory/models/file.py
> +
Tohle asi může být výš, ať se nedělají zbytečné operace na tom obrázku (ale to je nitpick)

2023-01-20 20:44 UTC, Sanqui commented on rhinventory/public_blueprints/magdb.py
> +
protip: existuje `defaultdict` (import z `collections`) pomocí kterého lze takovýhle kód napsat přímočařeji:

```python
    logos = defaultdict(set)
    for logo in MagazineIssueVersionFiles.query.filter(MagazineIssueVersionFiles.file_type==MagDBFileType.logo).all():
        magazine_id = logo.magazine_issue_version.magazine_issue.magazine_id
        logos[magazine_id].add(logo.file)
```

2023-01-23 14:45 UTC, tomascapek commented on rhinventory/admin_views/file.py
> -
No jo, to vyrobí sice `File`, ale necommituje ho to -> tudíž si myslím, že se duplikáty neuloží.

2023-01-23 14:45 UTC, tomascapek commented on rhinventory/admin_views/magdb.py
> +            prepared_values["issue_number"] = last_issue.issue_number or 0 + 1
Yep, zjistil jsem, ale necommitnul jsem.

2023-01-23 14:46 UTC, tomascapek commented on rhinventory/public_blueprints/magdb.py
> +
Díky za připomenutí!

2023-01-23 15:01 UTC, tomascapek commented on rhinventory/models/file.py
> +
Ok, tady jsem trošku nepřemýšlel.

2023-01-23 15:22 UTC, tomascapek commented on rhinventory/admin_views/file.py
> -
Fixed.

2023-01-23 15:31 UTC, merged